name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      # Check out the repo and set up Python
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Load cached dependencies if they exist
      - name: Load cached pip dependencies
        id: cached-pip-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ runner.os }}-${{ hashFiles('requirements*.txt') }}
      
      # Install dependencies
      - name: Install dependencies
        if: steps.cached-pip-dependencies.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      # Build documentation
      - name: Build Documentation
        run: |
          sphinx-apidoc -o docs/source nametable/
          sphinx-build docs/source public -b dirhtml

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          public_dir: ./public

      # Upload the artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: public
