name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      # Check out the repo and set up Python
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Load cached dependencies if they exist
      - name: Load cached dependencies
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-venv-
      
      - name: Install Dependencies
        run: python -m venv ./.venv && . ./.venv/bin/activate && pip install -r requirements-dev.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      # Build documentation
      - name: Build Documentation
        run: |
          source .venv/bin/activate
          sphinx-apidoc -o docs/source nametable/
          sphinx-build docs/source public -b dirhtml

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          public_dir: ./public

      # Upload the artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: public
