name: Tests

on:
  - push
  - pull_request

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo and set up Python
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          
      - name: Install Dependencies
        run: python -m venv ./.venv && . ./.venv/bin/activate && pip install -r requirements-dev.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      # Install and run linters
      - run: |
          source .venv/bin/activate
          flake8 . --max-line-length 120 --ignore=E203 --exclude .venv --per-file-ignores="__init__.py:F401"
          black . --check --line-length 120 --exclude .venv

  test:
    needs: linting
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      # Check out the repo and set up Python
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: python -m venv ./.venv && . ./.venv/bin/activate && pip install -r requirements-dev.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      # Run test suite
      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m pytest tests/ --exitfirst --verbose --failed-first
